//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInformation
    {
        public int Id { get; set; }
        public string Job_Position { get; set; }
        public string Company_Name { get; set; }
        public string Work_Address { get; set; }
        public string Job_Description { get; set; }
        public string Job_Requirement { get; set; }
        public string Person_to_Contact { get; set; }
        public string Contact_Number { get; set; }
        public string Contact_Email { get; set; }
        public string Other_Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
