//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Student_Id { get; set; }
        public string Full_Name { get; set; }
        public string Is_Maori_or_Pacific { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Contact_Number { get; set; }
        public string Email { get; set; }
        public string Physical_Address { get; set; }
        public string Postal_Address { get; set; }
        public string Institute { get; set; }
        public string Qualification_Title { get; set; }
        public Nullable<System.DateTime> Qualification_Completion_Date { get; set; }
        public string Enrollment_Status { get; set; }
        public string Job_Expection { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
