//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_Id { get; set; }
        public string Password { get; set; }
        public string Full_Name { get; set; }
        public string Is_Maori_or_Pacific { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Contact_Number { get; set; }
        public string Email { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual StudentCase StudentCase { get; set; }
    }
}
