//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Broker_Online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCase
    {
        public int Student_Id { get; set; }
        public string Full_Name { get; set; }
        public string Contact_Number { get; set; }
        public string Student_Email_Link { get; set; }
        public string Qualification_Title { get; set; }
        public string Recommanded_Job { get; set; }
        public string Progress { get; set; }
        public string Profile_Link { get; set; }
        public string Explanatory_Comment { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
